// ════════════════════════════════════════════
//  MOCK DATA — GéoPortail RESINA
//  Simule les réponses de l'API Spring Boot
// ════════════════════════════════════════════

export const MOCK_SITES = [
  {
    id: 'primature',
    nom: 'Primature',
    ville: 'Ouagadougou',
    region: 'Centre',
    latitude: 12.3569,
    longitude: -1.5330,
    netxmsNodeId: 1861,
    niveaux: 3,
    totalEquipements: 13,
    contactDsiNom: 'Moussa OUEDRAOGO',
    contactDsiTel: '+226 70 11 22 33',
    statut: 'ACTIF',
    infoSurvol: 'Hub central RESINA',
  },
  {
    id: 'mef',
    nom: "Ministère de l'Économie",
    ville: 'Ouagadougou',
    region: 'Centre',
    latitude: 12.3530,
    longitude: -1.5150,
    netxmsNodeId: 1842,
    niveaux: 4,
    totalEquipements: 8,
    contactDsiNom: 'Jean KABORE',
    contactDsiTel: '+226 70 44 55 66',
    statut: 'ACTIF',
    infoSurvol: 'Ministère des Finances',
  },
  {
    id: 'mtrans',
    nom: 'Ministère des Transports',
    ville: 'Ouagadougou',
    region: 'Centre',
    latitude: 12.3650,
    longitude: -1.5100,
    netxmsNodeId: 1666,
    niveaux: 3,
    totalEquipements: 10,
    contactDsiNom: 'Issouf TRAORE',
    contactDsiTel: '+226 70 44 55 66',
    statut: 'ACTIF',
    infoSurvol: 'Ministère des Transports',
  },
  {
    id: 'dgf',
    nom: 'Direction Générale des Finances',
    ville: 'Ouagadougou',
    region: 'Centre',
    latitude: 12.3490,
    longitude: -1.5200,
    netxmsNodeId: 2010,
    niveaux: 5,
    totalEquipements: 20,
    contactDsiNom: 'Ali SAWADOGO',
    contactDsiTel: '+226 70 22 33 44',
    statut: 'ACTIF',
    infoSurvol: 'DGF Ouagadougou',
  },
  {
    id: 'meducation',
    nom: "Ministère de l'Éducation",
    ville: 'Ouagadougou',
    region: 'Centre',
    latitude: 12.3480,
    longitude: -1.5300,
    netxmsNodeId: 1780,
    niveaux: 3,
    totalEquipements: 12,
    contactDsiNom: 'Fatimata ZONGO',
    contactDsiTel: '+226 70 55 66 77',
    statut: 'ACTIF',
    infoSurvol: 'Ministère Éducation',
  },
  {
    id: 'msante',
    nom: 'Ministère de la Santé',
    ville: 'Ouagadougou',
    region: 'Centre',
    latitude: 12.3600,
    longitude: -1.5250,
    netxmsNodeId: 1920,
    niveaux: 4,
    totalEquipements: 15,
    contactDsiNom: 'Rasmata ILBOUDO',
    contactDsiTel: '+226 70 11 22 99',
    statut: 'ACTIF',
    infoSurvol: 'Ministère Santé',
  },
  {
    id: 'gouv-sahel',
    nom: 'Gouvernorat du Sahel (Dori)',
    ville: 'Dori',
    region: 'Sahel',
    latitude: 14.0353,
    longitude: 0.0360,
    netxmsNodeId: 2087,
    niveaux: 2,
    totalEquipements: 6,
    contactDsiNom: 'Ibrahim COMPAORÉ',
    contactDsiTel: '+226 70 88 99 00',
    statut: 'ACTIF',
    infoSurvol: 'Gouvernorat — Région du Sahel',
  },
  {
    id: 'gouv-sudouest',
    nom: 'Gouvernorat Sud-Ouest (Gaoua)',
    ville: 'Gaoua',
    region: 'Sud-Ouest',
    latitude: 10.3310,
    longitude: -3.1780,
    netxmsNodeId: 3184,
    niveaux: 2,
    totalEquipements: 5,
    contactDsiNom: 'Salif BARRO',
    contactDsiTel: '+226 70 77 88 00',
    statut: 'ACTIF',
    infoSurvol: 'Gouvernorat Sud-Ouest',
  },
]

// Statuts ANPTIC par site (scénarios)
export const MOCK_ANPTIC = {
  'primature': {
    statut: 'OK',
    debitMontant: 65.0,
    debitDescendant: 130.0,
    typeLiaison: 'Fibre optique',
    qualiteSignal: 'Très bonne',
    latenceMs: 8,
    disponibilite30j: 99.9,
    derniereMaj: new Date().toISOString(),
  },
  'mef': {
    statut: 'KO',
    debitMontant: null,
    debitDescendant: null,
    typeLiaison: null,
    qualiteSignal: null,
    latenceMs: null,
    disponibilite30j: 87.3,
    indisponibleDepuis: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    derniereMaj: new Date().toISOString(),
  },
  'mtrans': {
    statut: 'WARN',
    debitMontant: 12.0,
    debitDescendant: 18.0,
    typeLiaison: 'VSAT',
    qualiteSignal: 'Dégradée',
    latenceMs: 420,
    disponibilite30j: 91.2,
    derniereMaj: new Date().toISOString(),
  },
  'dgf': {
    statut: 'OK',
    debitMontant: 100.0,
    debitDescendant: 200.0,
    typeLiaison: 'Fibre optique',
    qualiteSignal: 'Excellente',
    latenceMs: 4,
    disponibilite30j: 99.95,
    derniereMaj: new Date().toISOString(),
  },
  'meducation': {
    statut: 'WARN',
    debitMontant: 8.0,
    debitDescendant: 15.0,
    typeLiaison: 'VSAT',
    qualiteSignal: 'Dégradée',
    latenceMs: 380,
    disponibilite30j: 88.5,
    derniereMaj: new Date().toISOString(),
  },
  'msante': {
    statut: 'OK',
    debitMontant: 50.0,
    debitDescendant: 100.0,
    typeLiaison: 'Fibre optique',
    qualiteSignal: 'Bonne',
    latenceMs: 12,
    disponibilite30j: 99.1,
    derniereMaj: new Date().toISOString(),
  },
  'gouv-sahel': {
    statut: 'KO',
    debitMontant: null,
    debitDescendant: null,
    typeLiaison: null,
    qualiteSignal: null,
    latenceMs: null,
    disponibilite30j: 72.4,
    indisponibleDepuis: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    derniereMaj: new Date().toISOString(),
  },
  'gouv-sudouest': {
    statut: 'KO',
    debitMontant: null,
    debitDescendant: null,
    typeLiaison: null,
    qualiteSignal: null,
    latenceMs: null,
    disponibilite30j: 65.0,
    indisponibleDepuis: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    derniereMaj: new Date().toISOString(),
  },
}

export const MOCK_LAN = {
  'primature': {
    statut: 'INCIDENT',
    totalEquipements: 13,
    equipementsActifs: 8,
    equipementsPannes: 5,
    niveauxSurveilles: 3,
    derniereMaj: new Date().toISOString(),
    niveaux: [
      { code: 'RDC', libelle: 'Rez-de-chaussée', statut: 'INCIDENT', detail: '1 switch hors service sur 2 · réseau instable', equipementsActifs: 3, equipementsTotal: 4 },
      { code: 'R+1', libelle: 'Premier étage',   statut: 'INCIDENT', detail: '3 bornes Wi-Fi hors service sur 4', equipementsActifs: 1, equipementsTotal: 4 },
      { code: 'R+2', libelle: 'Deuxième étage',  statut: 'OK',       detail: 'Tout fonctionne · 4 équipements sur 4 actifs', equipementsActifs: 4, equipementsTotal: 5 },
    ],
  },
  'mef': {
    statut: 'OK',
    totalEquipements: 8,
    equipementsActifs: 8,
    equipementsPannes: 0,
    niveauxSurveilles: 2,
    derniereMaj: new Date().toISOString(),
    niveaux: [
      { code: 'RDC', libelle: 'Rez-de-chaussée', statut: 'OK', detail: 'Tout fonctionne · 4 équipements sur 4 actifs', equipementsActifs: 4, equipementsTotal: 4 },
      { code: 'R+1', libelle: 'Premier étage',   statut: 'OK', detail: 'Tout fonctionne · 4 équipements sur 4 actifs', equipementsActifs: 4, equipementsTotal: 4 },
    ],
  },
  'mtrans': {
    statut: 'ALERTE',
    totalEquipements: 10,
    equipementsActifs: 7,
    equipementsPannes: 3,
    niveauxSurveilles: 3,
    derniereMaj: new Date().toISOString(),
    niveaux: [
      { code: 'RDC', libelle: 'Rez-de-chaussée', statut: 'ALERTE', detail: '1 borne Wi-Fi hors service sur 3', equipementsActifs: 3, equipementsTotal: 4 },
      { code: 'R+1', libelle: 'Premier étage',   statut: 'ALERTE', detail: '2 bornes Wi-Fi hors service sur 4', equipementsActifs: 2, equipementsTotal: 4 },
      { code: 'R+2', libelle: 'Deuxième étage',  statut: 'OK',     detail: 'Tout fonctionne · 2 équipements sur 2 actifs', equipementsActifs: 2, equipementsTotal: 2 },
    ],
  },
  'dgf': {
    statut: 'OK',
    totalEquipements: 20,
    equipementsActifs: 20,
    equipementsPannes: 0,
    niveauxSurveilles: 5,
    derniereMaj: new Date().toISOString(),
    niveaux: [
      { code: 'RDC', libelle: 'Rez-de-chaussée', statut: 'OK', detail: 'Tout fonctionne · 4 équipements sur 4', equipementsActifs: 4, equipementsTotal: 4 },
      { code: 'R+1', libelle: 'Premier étage',   statut: 'OK', detail: 'Tout fonctionne · 4 équipements sur 4', equipementsActifs: 4, equipementsTotal: 4 },
      { code: 'R+2', libelle: 'Deuxième étage',  statut: 'OK', detail: 'Tout fonctionne · 4 équipements sur 4', equipementsActifs: 4, equipementsTotal: 4 },
      { code: 'R+3', libelle: 'Troisième étage', statut: 'OK', detail: 'Tout fonctionne · 4 équipements sur 4', equipementsActifs: 4, equipementsTotal: 4 },
      { code: 'R+4', libelle: 'Quatrième étage', statut: 'OK', detail: 'Tout fonctionne · 4 équipements sur 4', equipementsActifs: 4, equipementsTotal: 4 },
    ],
  },
  'meducation': {
    statut: 'ALERTE',
    totalEquipements: 12,
    equipementsActifs: 9,
    equipementsPannes: 3,
    niveauxSurveilles: 3,
    derniereMaj: new Date().toISOString(),
    niveaux: [
      { code: 'RDC', libelle: 'Rez-de-chaussée', statut: 'OK',     detail: 'Tout fonctionne · 4 équipements sur 4', equipementsActifs: 4, equipementsTotal: 4 },
      { code: 'R+1', libelle: 'Premier étage',   statut: 'ALERTE', detail: '2 bornes Wi-Fi hors service sur 4', equipementsActifs: 2, equipementsTotal: 4 },
      { code: 'R+2', libelle: 'Deuxième étage',  statut: 'ALERTE', detail: '1 switch hors service sur 2', equipementsActifs: 3, equipementsTotal: 4 },
    ],
  },
  'msante': {
    statut: 'OK',
    totalEquipements: 15,
    equipementsActifs: 15,
    equipementsPannes: 0,
    niveauxSurveilles: 4,
    derniereMaj: new Date().toISOString(),
    niveaux: [
      { code: 'RDC', libelle: 'Rez-de-chaussée', statut: 'OK', detail: 'Tout fonctionne · 4 équipements sur 4', equipementsActifs: 4, equipementsTotal: 4 },
      { code: 'R+1', libelle: 'Premier étage',   statut: 'OK', detail: 'Tout fonctionne · 4 équipements sur 4', equipementsActifs: 4, equipementsTotal: 4 },
      { code: 'R+2', libelle: 'Deuxième étage',  statut: 'OK', detail: 'Tout fonctionne · 4 équipements sur 4', equipementsActifs: 4, equipementsTotal: 4 },
      { code: 'R+3', libelle: 'Troisième étage', statut: 'OK', detail: 'Tout fonctionne · 3 équipements sur 3', equipementsActifs: 3, equipementsTotal: 3 },
    ],
  },
  'gouv-sahel': {
    statut: 'OK',
    totalEquipements: 6,
    equipementsActifs: 6,
    equipementsPannes: 0,
    niveauxSurveilles: 2,
    derniereMaj: new Date().toISOString(),
    niveaux: [
      { code: 'RDC', libelle: 'Rez-de-chaussée', statut: 'OK', detail: 'Tout fonctionne · 3 équipements sur 3', equipementsActifs: 3, equipementsTotal: 3 },
      { code: 'R+1', libelle: 'Premier étage',   statut: 'OK', detail: 'Tout fonctionne · 3 équipements sur 3', equipementsActifs: 3, equipementsTotal: 3 },
    ],
  },
  'gouv-sudouest': {
    statut: 'INCIDENT',
    totalEquipements: 5,
    equipementsActifs: 2,
    equipementsPannes: 3,
    niveauxSurveilles: 2,
    derniereMaj: new Date().toISOString(),
    niveaux: [
      { code: 'RDC', libelle: 'Rez-de-chaussée', statut: 'INCIDENT', detail: '2 bornes Wi-Fi hors service sur 3 · 1 switch KO', equipementsActifs: 1, equipementsTotal: 4 },
      { code: 'R+1', libelle: 'Premier étage',   statut: 'OK',       detail: 'Tout fonctionne · 1 équipement sur 1', equipementsActifs: 1, equipementsTotal: 1 },
    ],
  },
}

export const MOCK_ALERTES = [
  {
    id: 'a1',
    siteId: 'gouv-sahel',
    siteNom: 'Dori — Gouvernorat du Sahel',
    type: 'PANNE_ANPTIC',
    statutColor: 'ko',
    message: 'Connexion ANPTIC hors service depuis 07h45. Équipe NOC mobilisée.',
    lu: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'a2',
    siteId: 'mtrans',
    siteNom: 'Ministère des Transports',
    type: 'WARN_ANPTIC',
    statutColor: 'warn',
    message: 'Débit dégradé détecté : 12 Mbit/s au lieu de 100 Mbit/s. Diagnostic en cours.',
    lu: false,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'a3',
    siteId: 'gouv-sudouest',
    siteNom: 'Gaoua — Gouvernorat Sud-Ouest',
    type: 'PANNE_LAN',
    statutColor: 'ko',
    message: 'Panne LAN : 3 bornes Wi-Fi hors service au R+1. Contacter votre DSI.',
    lu: false,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'a4',
    siteId: 'mef',
    siteNom: "Ministère de l'Économie",
    type: 'RETABLISSEMENT',
    statutColor: 'ok',
    message: 'Connexion ANPTIC rétablie. Débit normal : 65/130 Mbit/s.',
    lu: true,
    createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'a5',
    siteId: 'primature',
    siteNom: 'Primature',
    type: 'RETABLISSEMENT',
    statutColor: 'ok',
    message: 'Réseau LAN entièrement opérationnel après intervention DSI.',
    lu: true,
    createdAt: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
  },
]

export const MOCK_DASHBOARD = {
  sitesActifs: 47,
  sitesTotal: 54,
  sitesDisponibles: 43,
  sitesDegrades: 2,
  sitesHorsService: 2,
  sitesEnAlerte: [
    { id: 'gouv-sahel',    nom: 'Gouvernorat du Sahel (Dori)',  ville: 'Dori',        statutAnptic: 'KO',   statutLan: 'OK',       derniereMaj: '2h15' },
    { id: 'gouv-sudouest', nom: 'Gouvernorat Sud-Ouest (Gaoua)',ville: 'Gaoua',       statutAnptic: 'KO',   statutLan: 'INCIDENT', derniereMaj: '5h00' },
    { id: 'mtrans',        nom: 'Ministère des Transports',     ville: 'Ouagadougou', statutAnptic: 'WARN', statutLan: 'OK',       derniereMaj: '30min' },
    { id: 'meducation',    nom: "Ministère de l'Éducation",     ville: 'Ouagadougou', statutAnptic: 'WARN', statutLan: 'ALERTE',   derniereMaj: '1h00' },
  ]
}

export const MOCK_AUDIT_LOG = [
  { id: 1, date: '11/06/2026 09h14', utilisateur: 'KIWALO X.', action: 'Modification coordonnées GPS', entite: 'Gouvernorat Sahel (Dori)', detail: 'lat 14.0353, lon 0.0360' },
  { id: 2, date: '10/06/2026 14h42', utilisateur: 'OUEDRAOGO A.', action: 'Ajout équipement LAN', entite: 'AP-R1-02 (Borne Wi-Fi, R+1) — Ministère de l\'Économie', detail: '' },
  { id: 3, date: '10/06/2026 11h29', utilisateur: 'KIWALO X.', action: 'Modification seuil d\'alerte', entite: 'Débit minimal : 8 Mbit/s → 10 Mbit/s', detail: '' },
  { id: 4, date: '09/06/2026 10h08', utilisateur: 'OUEDRAOGO A.', action: 'Création site', entite: 'Mairie de Manga (Zoundweogo)', detail: 'nœud NetXMS 3210' },
  { id: 5, date: '09/06/2026 10h45', utilisateur: 'KIWALO X.', action: 'Suppression token push expiré', entite: 'Protocole (Primature)', detail: 'Token …c1d8' },
  { id: 6, date: '08/06/2026 09h30', utilisateur: 'KABORE S.', action: 'Mise à jour contact DSI', entite: 'Ministère des Transports', detail: 'Issouf TRAORE +226 70 44 55 66' },
]

export const MOCK_UTILISATEURS = [
  { id: 1, nom: 'KIWALO', prenom: 'Xavier', email: 'x.kiwalo@anptic.bf', role: 'ADMIN_GLOBAL', actif: true, createdAt: '01/01/2026' },
  { id: 2, nom: 'OUEDRAOGO', prenom: 'Abdoul', email: 'a.ouedraogo@anptic.bf', role: 'ADMIN_SITE', actif: true, createdAt: '15/02/2026' },
  { id: 3, nom: 'KABORE', prenom: 'Salimata', email: 's.kabore@anptic.bf', role: 'ADMIN_SITE', actif: true, createdAt: '20/03/2026' },
]

export const MOCK_PUSH_TOKENS = [
  { id: 1, profil: 'Ministre (Primature)', sites: ['Primature'], plateforme: 'Android', enregistreLe: '02/06/2026', statut: 'ACTIF' },
  { id: 2, profil: 'SG du MTDPCE', sites: ['Primature', "Min. Économie"], plateforme: 'Android', enregistreLe: '03/06/2026', statut: 'ACTIF' },
  { id: 3, profil: 'Protocole (Primature)', sites: ['Primature'], plateforme: 'iOS', enregistreLe: '05/06/2026', statut: 'EXPIRE' },
]
